[versions]
agp = "8.13.1"
concurrentFutures = "1.3.0"
datastorePreference = "1.1.7"
guava = "33.5.0-android"
videoApiClient = "1.6.7"
androidxActivity = "1.10.1"
androidxAppcompat = "1.7.1"
androidxCamera = "1.4.0-alpha13"
androidxConstraintlayout = "2.2.1"
androidxCore = "1.17.0"
androidxDatabinding = "8.13.0"
androidxEspresso = "3.7.0"
androidxJunit = "1.3.0"
androidxLifecycle = "2.9.3"
androidxLifecycleExtensions = "2.2.0"
androidxNavigation = "2.9.6"
androidxPreference = "1.2.1"
androidxTest = "1.7.0"
androidxWindow = "1.4.0"
dokka = "2.1.0"
junit = "4.13.2"
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
kotlinxIo = "0.8.0"
material = "1.13.0"
mockk = "1.14.5"
robolectric = "4.16"
komuxer = "0.3.1"
srtdroid = "1.9.5"
junitKtx = "1.3.0"

[libraries]
android-documentation-plugin = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "dokka" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastorePreference" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreference" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
video-api-client = { module = "video.api:android-api-client", version.ref = "videoApiClient" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-camera-viewfinder-view = { module = "androidx.camera.viewfinder:viewfinder-view", version.ref = "androidxCamera" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-databinding-common = { module = "androidx.databinding:databinding-common", version.ref = "androidxDatabinding" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidxLifecycleExtensions" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidxPreference" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTest" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-test-ext-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidxWindow" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
junit = { module = "junit:junit", version.ref = "junit" }
komedia-komuxer-rtmp = { module = "io.github.komedia.komuxer:rtmp", version.ref = "komuxer" }
komedia-komuxer-flv = { module = "io.github.komedia.komuxer:flv", version.ref = "komuxer" }
komedia-komuxer-avutil = { module = "io.github.komedia.komuxer:av-util", version.ref = "komuxer" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
srtdroid-ktx = { module = "io.github.thibaultbee.srtdroid:srtdroid-ktx", version.ref = "srtdroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

